# 数据操作
> 2025.3.14

导入`torch`库

In [ ]:
import torch

`张量`表示一个数值组成的数组，可能有多个维度

In [ ]:
x = torch.arange(12)
x

通过张量的`shape`属性访问张量的*形状*和张量中的元素总数

In [ ]:
x.shape

In [ ]:
x.numel()

要改变张量的形状而不改变元素数量和元素值，用`reshape`

In [10]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

有专用的全0，全1，其他常量或者从特定分布中随机采样的数字的方法
> 注：(通道\*高\*宽)

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

可以用字面量来为张量中每个元素赋予特定值
> 注： n个中括号为n维，二维=行*列，三维=层(深度)\*行\*列
>
> 可使用.shape打印维度(形状)

In [16]:
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [17]:
torch.tensor([[[2,1,4,3],[1,2,3,4],[4,3,2,1]]]) .shape

torch.Size([1, 3, 4])

常见标准算数运算符(`+`,`-`,`*`,`/`,`**`)可以被升级为按元素运算

In [18]:
a = torch.tensor([1.0, 2, 4, 8]) #1.0声明为浮点数
b = torch.tensor([2, 2, 2, 2])
a+b,a-b,a*b,a/b,a**b

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

可以把多个张量连结在一起
> 注： 使用cat函数，第一个参数为需要连结的张量
>
> 第二个参数`dim`表示第几维度，维度0=列，维度1=行 (理解为从外到内第几层中括号)

In [19]:
x = torch.arange(12, dtype=torch.float32).reshape(3,4)
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((x,y),dim=0), torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符构建二元张量

In [20]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量所有元素求和得到一个元素张量

In [21]:
x.sum()

tensor(66.)

形状不同，我们可以使用`广播机制`(broadcasting mechanism) 来执行按元素操作 (从numpy来的)

In [24]:
n = torch.arange(3).reshape((3,1))
m = torch.arange(2).reshape((1,2))
n,m

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [23]:
n + m

tensor([[0, 1],
        [1, 2],
        [2, 3]])

可以用`[-1]`选择最后一个元素，可以用`[1:3]`选择第二个和第三个元素

In [25]:
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

也可以指定索引来写入元素

In [26]:
x[1,2] = 9
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

当然也可以为多个元素赋相同值，只需要索引所有元素并赋值

In [27]:
x[0:2,:] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

某些操作会导致为新结果分配内存，我们最好执行原地操作

In [28]:
z = torch.zeros_like(y)
print('id(z)', id(z))
z[:] = x + y
print('id(z)', id(z))

id(z) 2157617864848
id(z) 2157617864848
