# 线性代数
> 2025.3.15

## 标量

In [54]:
import torch
x = torch.tensor([3.0])
y = torch.tensor([2.0])

x+y, x*y, x/y, x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

## 向量
将向量是为标量值组成的列表

In [55]:
x = torch.arange(4, dtype=torch.float32)
x

tensor([0., 1., 2., 3.])

通过索引访问任一元素

In [56]:
x[3]

tensor(3.)

访问张量长度和形状

In [57]:
len(x)

4

In [58]:
x.shape

torch.Size([4])

## 矩阵
通过指定两个分量来创建一个M*N的矩阵

In [59]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

实现矩阵转置

In [60]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

尝试一个对称矩阵，即$A = A^{T}$

In [61]:
B = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [62]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 张量及运算
矩阵可以如同向量推广，可以构建具有更多轴的数据结构
> 注： 下面矩阵中为`reshape(层，行，列)`

In [63]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

具有相同形状的张量，任何按元素二元运算的结果是相同形状的张量

In [64]:
A = torch.arange(20, dtype = torch.float32).reshape(5,4)
B = A.clone()
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵相乘

In [65]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

张量加乘上一个标量会自动广播，使得每个元素都会与之相加相乘，不会改变形状

In [66]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 降维
计算任意形状张量元素和


In [67]:
A = torch.arange(20*2, dtype=torch.float32).reshape(2,5,4)
A.shape, A.sum()

(torch.Size([2, 5, 4]), tensor(780.))

也可以按照指定的轴来求和（维度与维度之间进行求和，从而将改维度值降为0）
先打印A记住它原来的样子

In [68]:
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

`axis`表示第几维

In [69]:
A_sum_axis0 = A.sum(axis=0)     #层之间进行运算将维度从3降至2
A_sum_axis0, A_sum_axis0.shape

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]),
 torch.Size([5, 4]))

In [70]:
A_sum_axis1 = A.sum(axis=1)     #各行相加,保留层与列，将维度降至2（第二个方括号里的内容相加）
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]]),
 torch.Size([2, 4]))

求均值可以用`mean()`或`sum() / numel()`总和除以总数

In [71]:
A.mean() ,A.sum() / A.numel()

(tensor(19.5000), tensor(19.5000))

### 非降维求和
计算总和或均值是保持轴(层)数不变

In [72]:
sum_A = A.sum(axis=1, keepdim=True)
sum_A

tensor([[[ 40.,  45.,  50.,  55.]],

        [[140., 145., 150., 155.]]])

可以通过广播将`A`除以`sum_A`(维度相同)

In [73]:
A / sum_A

tensor([[[0.0000, 0.0222, 0.0400, 0.0545],
         [0.1000, 0.1111, 0.1200, 0.1273],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.3000, 0.2889, 0.2800, 0.2727],
         [0.4000, 0.3778, 0.3600, 0.3455]],

        [[0.1429, 0.1448, 0.1467, 0.1484],
         [0.1714, 0.1724, 0.1733, 0.1742],
         [0.2000, 0.2000, 0.2000, 0.2000],
         [0.2286, 0.2276, 0.2267, 0.2258],
         [0.2571, 0.2552, 0.2533, 0.2516]]])

也可以计算某个维度的累积和

In [74]:
A.cumsum(axis=1)

tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   6.,   8.,  10.],
         [ 12.,  15.,  18.,  21.],
         [ 24.,  28.,  32.,  36.],
         [ 40.,  45.,  50.,  55.]],

        [[ 20.,  21.,  22.,  23.],
         [ 44.,  46.,  48.,  50.],
         [ 72.,  75.,  78.,  81.],
         [104., 108., 112., 116.],
         [140., 145., 150., 155.]]])

## 矩阵点积
相同位置按元素乘积和

In [75]:
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

## 矩阵向量积
$Ax$为一个长度为m的列向量

In [77]:
A = torch.arange(20, dtype = torch.float32).reshape(5,4)
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 矩阵乘法

In [78]:
B = torch.ones(4,3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

## 范数
$L_2$范数是向量元素平方和的平方根

In [79]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

$L_1$范数是向量元素绝对值和

In [80]:
torch.abs(u).sum()

tensor(7.)

则推广至$L_p$范数：
$$
\lvert \lvert x \rvert \rvert_p=(\sum_{i=1}^{n} \lvert x_i \rvert ^p)^\frac{1}{p}
$$

类似于$L_2$范数，矩阵的佛罗贝尼乌斯范数是所有元素平方和的平方根

In [81]:
torch.norm(torch.ones((4,9)))

tensor(6.)